# Generated by Django 3.2.4 on 2023-09-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('mobile', models.CharField(max_length=25, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='donateus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/donator')),
                ('mobile', models.CharField(max_length=30, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('address', models.TextField(null=True)),
                ('pincode', models.CharField(max_length=15, null=True)),
                ('rupees', models.IntegerField(null=True)),
                ('ddate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='nhelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('mobile', models.CharField(max_length=30, null=True)),
                ('helptype', models.CharField(max_length=200, null=True)),
                ('message', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/picture')),
                ('request_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headlines', models.TextField(null=True)),
                ('slider_dec', models.TextField(null=True)),
                ('slider_picture', models.ImageField(null=True, upload_to='static/slider/')),
            ],
        ),
        migrations.CreateModel(
            name='upcomingevent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_picture', models.ImageField(null=True, upload_to='static/event/')),
                ('event_title', models.CharField(max_length=200, null=True)),
                ('event_details', models.TextField()),
                ('event_date', models.DateField()),
                ('event_place', models.CharField(max_length=300)),
                ('event_purpose', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='volunteer',
            fields=[
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('current_position', models.CharField(max_length=100, null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/volunteer')),
            ],
        ),
    ]
