# Generated by Django 3.2.4 on 2023-09-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='schange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('picture', models.ImageField(null=True, upload_to='static/picture')),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
